# Copyright (c) Rodrigo Speller. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

name: CIEmu
description: |
  CIEmu enables seamless and efficient multi-arch emulation for Linux containers, allowing to easily run Linux
  containers with a specific CPU architecture on GitHub Actions workflows.

inputs:
  image:
    description: The image base to be used for emulation.
    default: alpine
    required: false
  cache-prefix:
    description: The prefix of the cache to be used to store the built image. If not specified, the image name will be used.
    required: false
    default: ""
  shell:
    description: The shell to execute the 'build' and 'run' commands.
    default: /bin/sh
    required: false
  build:
    description: The commands to be executed to build the image for this container.
    default: ""
    required: false
  bind:
    description: A space-separated list of volume bindings for this container.
    default: ""
    required: false
  env:
    description: A space-separated list of environment variables names to be exported for this container.
    default: ""
    required: false
  user: 
    description: The user to be used within the running container. By default, Docker uses the root user and group, but
      CIEmu Action, uses the current user and group that is executing the workflow.
    default: ""
    required: false
  run:
    description: The commands to be executed to run the container.
    default: ""
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
