#!/bin/sh
# Copyright (c) Rodrigo Speller. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

set -e

basedir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if [ "$GITHUB_ACTIONS" = "true" ]; then
    node "$basedir/dist/index.js" "$@"
else
    npx ts-node "$basedir/src/main" "$@"
fi
