name: Getting started with CIEmu Action

on: [ push, pull_request ]

jobs:
  getting-started:
    name: Running on ${{ matrix.image }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          # Alpine 3.17 images
          - image: amd64/alpine:3.17
          - image: arm32v6/alpine:3.17
          - image: arm32v7/alpine:3.17
          - image: arm64v8/alpine:3.17
          - image: ppc64le/alpine:3.17
          - image: s390x/alpine:3.17
          # Alpine Edge image
          - image: riscv64/alpine:edge
          # Ubuntu Jammy images
          - image: amd64/ubuntu:jammy
          - image: arm32v7/ubuntu:jammy
          - image: arm64v8/ubuntu:jammy
          - image: ppc64le/ubuntu:jammy
          - image: s390x/ubuntu:jammy
          # Ubuntu Bionic image
          - image: i386/ubuntu:bionic
          
    steps:
      - name: Executing CIEmu
        uses: ciemu/action@v0
        env: 
          CIEMU_IMAGE: ${{ matrix.image }}
        with:
          # Image base
          image: ${{ matrix.image }}
          # Caching
          cache-prefix: cache-getting-started-${{ matrix.image }}
          # Build image
          build: |
            set -e

            # Install dependencies

            case '${{ matrix.image }}' in
              *alpine*)
                apk add --no-cache wget
                ;;
              *ubuntu*)
                apt-get update -y
                apt-get install -y wget
                ;;
            esac

            # Install chipsay
            wget -O /usr/local/bin/chipsay https://raw.githubusercontent.com/ciemu/action/v0/chipsay
            chmod 755 /usr/local/bin/chipsay
          # Run container
          bind: |
            /home:/mnt/custom1:ro
            /home:/mnt/custom2:ro
          env: |
            CIEMU_IMAGE
          run: |
            chipsay
